name: Proton Valve xbe nopackage Arch Linux CI

on:
  schedule:
    - cron:  '45 8,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo lib32-jack2
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp
          export CARGO_HOME="$PWD"
          cd proton-tkg
          sed -i 's/distro=""/distro="archlinux"/' proton-tkg.cfg
          sed -i 's/uninstaller="false"/uninstaller="true"/' proton-tkg.cfg
          sed -i 's/autoinstall="false"/autoinstall="true"/' proton-tkg.cfg
          echo >> "_proton_tar_built='true'"
          yes|./proton-tkg.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: proton-tkg-build
          path: proton-tkg/built/*.tar
